### PR TITLE
Build arm64 binaries

### PR DESCRIPTION
**Pull request by mesaugat**
### Changes

* Update `goreleaser.yml` that supports the latest version of `goreleaser v0.184.0`
* Regenerate `go.sum` to remove old artifacts from the file
* Use go 1.17 in `.travis.yml`

### Build

`goreleaser build` seems to be working as expected. 

```
goreleaser build --skip-validate --rm-dist

 • loading go mod information
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • writing                   changelog=dist/CHANGELOG.md
   • building binaries
      • building                  binary=/Users/saugat/Code/nepcal/dist/nepcal_windows_amd64/nepcal.exe
      • building                  binary=/Users/saugat/Code/nepcal/dist/nepcal_darwin_arm64/nepcal
      • building                  binary=/Users/saugat/Code/nepcal/dist/nepcal_linux_amd64/nepcal
      • building                  binary=/Users/saugat/Code/nepcal/dist/nepcal_darwin_amd64/nepcal
      • building                  binary=/Users/saugat/Code/nepcal/dist/nepcal_windows_arm64/nepcal.exe
      • building                  binary=/Users/saugat/Code/nepcal/dist/nepcal_linux_arm64/nepcal
   • build succeeded after 0.67s

```

@srishanbhattarai Please release a new version of `nepcal` which supports `arm64`. 🙏

### CODE REVIEW

**Comment by srishanbhattarai** [comment]
Ok, I'll take a look. It's nice to have multi-arch binaries in general, but I'm curious if there is a specific use case that's motivating this?

**Comment by mesaugat** [comment]
@srishanbhattarai The motivation is that I use a M1 Macbook Pro and so do many others. 😅

Right now the nepcal amd64 binary works with Rosetta2, not natively.

**Comment by srishanbhattarai** [comment]
Ok, a new [release](https://github.com/srishanbhattarai/nepcal/releases/tag/v1.2.1) is out. Let me know if there are any issues.

My story on getting this to work.
- I needed to also upgrade the Go version in `go.mod` (c7381b5282e37704f54549d66e3b7fee0b5a6c51). 
- After that, the darwin arm64 binary was not being built (linux arm64 was built), so I realized I had goreleaser 0.149.0, whereas you said you had 0.184.0. Then, AS RECOMMENDED FROM THEIR WEBSITE, I reinstalled/upgraded goreleaser via brew, which just installs 0.149.0.
-  I find this hilarious - goreleaser is literally a program for making releases, and for some reason, they themselves cannot competently release their own program.
- Anyway, I found that 1.0.0 is out for goreleaser, so I had to install it manually via `go install`

**Comment by mesaugat** [comment]
@srishanbhattarai I can confirm that the brew tap works. Thanks for the quick turnaround.

```
Updated 3 taps (homebrew/core, homebrew/cask and srishanbhattarai/nepcal).

==> Upgrading srishanbhattarai/nepcal/nepcal
  1.2.0 -> 1.2.1
```

**Pull request merged**
